version: '3.1'
services:
  questionDB:
    container_name: questionDB
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: question
    ports:
      - '2345:5432'
    restart: unless-stopped

  quizDB:
    container_name: quizDB
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: quiz
    ports:
      - '3456:6543'
    restart: unless-stopped

  question-service:
    container_name: question-service
    build:
      context: ./question-service/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - questionDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://questionDB:5432/question
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    restart: unless-stopped