spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        ## Question
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/api/v1/question/**
        ## Quiz
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/v1/quiz/**


server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




